JDASoftwareGroup/kartothek

.coveragerc, .travis.yml, README.md
This adds a coverage report and publishes on codecov.io
example: https://codecov.io/gh/fjetter/kartothek/branch/add_coverage
=> Add coverage report

CHANGES.rst, kartothek/core/common_metadata.py
Discovered while working on #28.
Remove the hack we had for pre-0.10 pyarrow versions and implement
categorical-stripping in a proper way.
=> Arrow-based dict-type normalization

CHANGES.rst, asv_bench/benchmarks/index.py, kartothek/core/index.py, test-requirements.in, tests/core/test_index.py
Command used to run benchmarks: `asv run --python=same --show-stderr --bench=Index.track_mem_serialized`
Diff of benchmark results (`diff old.txt new.txt`) :
```
< [100.00%] ··· =============== =================== =================================== ==========
<                number_values   number_partitions                 dtype
<               --------------- ------------------- ----------------------------------- ----------
<                      10                10           (<class 'int'>, DataType(int64))     1145
<                      10                10          (<class 'str'>, DataType(string))     1206
<                      10               1000          (<class 'int'>, DataType(int64))    128558
<                      10               1000         (<class 'str'>, …
```
=> Implement efficient partial index serialization

kartothek/io/dask/delayed.py, kartothek/io/testing/update.py, kartothek/io/testing/utils.py, requirements.in, tests/conftest.py, tests/io/dask/bag/test_write.py, tests/io/dask/dataframe/test_read.py, tests/io/dask/dataframe/test_update.py, tests/io/dask/delayed/test_delete.py, tests/io/dask/delayed/test_gc.py, tests/io/dask/delayed/test_merge.py, tests/io/dask/delayed/test_read.py, tests/io/dask/delayed/test_update.py, tests/io/dask/delayed/test_write.py, tests/io_components/test_dataset_metadata_factory.py
1. Do never ever pickle stores (this is dangerous depending on the store
implementation due to open connections / file handles).
2. Ensure dask bags/tasks/ddf can be stock-pickled. Distributed tries to
use stock (c)pickle first and only falls back to slow cloudpickle if
this doesn't work. For production usage, let's ensure that we can use
stock pickle for all our computation graphs.
=> Pickle hardening / improvements

test-requirements.in
Using `pytest==4.4.0` I was getting `pytest: error: unrecognized arguments: --strict-markers` on master.
This flag is only supported starting from pytest 4.5.0, see: https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst.
=> update pytest version to `4.5.0` to support "--strict-markers"

CHANGES.rst, kartothek/core/common_metadata.py, kartothek/io/testing/write.py, kartothek/io_components/metapartition.py, kartothek/io_components/write.py
For a very common usecase where different computation branches (e.g.
dask items, iterator elements) produce different partitions, let's try
to be more helpful for the user and tell them which part of the dataset
are not compatible.
=> improve schema origin handling

CHANGES.rst, kartothek/core/common_metadata.py, kartothek/core/utils.py, kartothek/io/testing/read.py, kartothek/io_components/metapartition.py
Pandas schema metadata saved using python2 stores column names as type `bytes` given that that is how Python2 implements strings by default.
When this schema metadata is loaded using Python3, `kartothek.core.common_metadata.empty_dataframe_from_schema`retrieves these column names as if they were `bytes` objects. However, the column names in Parquet are still strings, so when kartothek  attempts to retrieve these `bytes` object columns it return nulls as there is no data stored for `bytes` columns. 
AFAIK this only affects `io.eager.read_table`.
For `pyarrow>=0.13`, we can create an empty pandas dataframe without using this pandas metadata. By doing so, kartothek remains compatible with schemas created in Python2.
=> Ensure column names are read as `str`

CHANGES.rst, kartothek/io/dask/delayed.py, kartothek/io/eager.py, kartothek/io/testing/delete.py, kartothek/io_components/gc.py
Continuation of: https://github.com/JDASoftwareGroup/kartothek/pull/64
Summary: call GC in functions which delete the entire dataset to remove possible unreferenced files.
Added the test `kartothek.io.testing.delete.test_delete_dataset_unreferenced_files`.
Two minor bugs where found in GC functions, when passed a `ds_factory` instead of a `store` and `dataset_uuid`. These were fixed
Original author: @mganesh1308
=> Call garbage collection in delete pipelines

CHANGES.rst, kartothek/io/dask/bag.py, kartothek/io/eager.py, tests/io/dask/bag/test_index.py
We could argue if the function should be placed in `delayed` or in `bag`. While it is internally implemented using `Dask.Bag`, the return type just behaves as a usual delayed computation, so I would opt for "implementation detail".
=> Dask index build

docs/changes.rst, docs/index.rst, docs/versioning.rst
This should set the boundaries for the versioning guarantees. Differently to the proposal in #57 this documentation now imposes full semver on `io` and `serialization` while reduced guarantees for `io_component` and `core` are provided.
=> Add doc section about versioning

CHANGES.rst, kartothek/io/dask/bag.py
Earlier, we called `.to_delayed()` on the `Item` object to convert it to
a `dask.Delayed` object. This however is more than just a conversion but
also calls the optimizer. If the `Item` is used in a broader context,
this optimization is too early and can lead to unexpected behavior as
demonstrated in the following example:
Imagine a bag that with 2 single-sized partitions:
bag := read_from_db_{0,1}
These partitions are now pre-processed twice for 2 calls to
`store_bag_as_dataset`:
bag_a := bag->pluck("a")
bag_b := bag->pluck("b")
Then, `store_bag_as_dataset` is called twice and a final reduction is
added:
ds_a = bag_a->store_bag_as_dataset("a")
ds_b = bag_b->store_bag_as_dataset("b")
result = reduce([ds_a, ds_b])
The user would very likely expect the following computation graph: …
=> store_bag_as_dataset now returns dask.bag.Item

CHANGES.rst, kartothek/io_components/docs.py, kartothek/serialization/_generic.py, tests/serialization/test_filter.py
Categoricals have an issue with the numpy issubdtype, hence the mapping to the kind attribute of the arrays/type
To properly support the predicate eval range, I added a section about the handling of the categoricals. IMHO we should support it but highlight that it may come with undesired negative side effects.
=> Enable filter_array_like properly for categoricals

.travis.yml, setup.cfg
No need to run coverage for every local test execution. When I run this in docker this adds >30s to test runtime at the end to collect the files, etc.
Executing it on travis should be sufficient
=> Do not execute coverage reports locally

kartothek/io/dask/dataframe.py
If the Parameter section isn't mentioned, the default_docs decorator cannot add the appropriate descriptions
=> Add Parameters section to read_dataset_as_ddf

CHANGES.rst, kartothek/io/dask/_utils.py, kartothek/io/dask/bag.py, kartothek/io/dask/delayed.py, tests/io/dask/bag/test_read.py
The implementation is nearly the same as in dask.delayed. Shared
functions have been moved to kartothek.io.dask._utils
=> Add functionality to read dataset using dask bag

.travis.yml
pip 19.2.1 was released yesterday but the issue with `find_links` while using `pip-compile` shows up there too so specifying that `pip` be upgraded to the latest `19.1.*` version.
=> Use a pip version less than 19.2

CHANGES.rst, kartothek/io/dask/bag.py, kartothek/io_components/docs.py, tests/io/dask/bag/test_read.py
Adding a keyword `partition_size` to the read functionalities for dask's bag
backend makes it possible to control the size of dask partitions when creating
the bag `db.from_sequence(some_sequence, partition_size)`. For example,`mps
= db.from_sequence(metapartitions, partition_size=100)` would create
dask partitions containing 100 elements of `metapartitions`.
=> Add keyword for controlling partitions size for dask bag

.travis.yml, ci/compile_requirements.sh
The most recent Dask versions require a more recent arrow version but the packages do not expose this information
=> Pin dask for pyarrow 0.12.1

CHANGES.rst, kartothek/io/dask/_update.py, tests/io/dask/dataframe/test_update.py
Makes `update_dataset_from_ddf` behave the same if called with empty ddf regardless of `shuffle` setting.
Closes #109
=> Streamline behavior of `update_dataset_from_ddf` with empty ddf.

CHANGES.rst, kartothek/core/dataset.py, kartothek/core/index.py, tests/core/test_index.py
`IndexBase.as_flat_series` now exposes the `date_as_object` flag from `pyarrow.Table.to_pandas`.
The default behaviour (`True`) remains unchanged.
=> Add date_as_object flag in core/index.py as_flat_series

setup.py
When building python distributions (e.g. wheels), some test packages where also bundled, although clearly that was not the intention of the code in `setup.py`, which only excluded the toplevel `tests` package. Changed to exclude *all* test packages.
=> Do not bundle tests

CHANGES.rst, kartothek/io_components/docs.py, kartothek/io_components/metapartition.py, tests/io_components/test_metapartition.py
This PR makes `io_components/metapartiton.py -> load_dataframes` raise a `ValueError` in case at least one table specified in the `columns` argument dict doesn't exist. 
The behavior to ignore a non-existent table specified in the `tables` argument remains unchanged.
=> Make load_dataframes raise, if non-existent table in columns argument

.readthedocs.yml
By default, readthedocs will use setuptools install to set up the doc build.
This may lead to build errors for non-python dependencies since we get some
coupling to their packaging implementations (e.g. without this it was tried
to compile a rust package). This way we can force it to explicitly use pre
packaged wheels.
=> Add explicit readthedocs configuration

CHANGES.rst, kartothek/serialization/_parquet.py, tests/serialization/test_filter.py, tests/serialization/test_parquet.py
Benchmark code (on local filesystem):
```
from functools import partial
from tempfile import TemporaryDirectory
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import storefact
from kartothek.io.eager import store_dataframes_as_dataset
from kartothek.serialization import ParquetSerializer
tmpdir = TemporaryDirectory().name
store_factory = partial(storefact.get_store_from_url, f"hfs://{tmpdir}")
df = pd.DataFrame({"x": np.tile([17, 18], 10 ** 6)})
uuid = "test"
dm = store_dataframes_as_dataset(store=store_factory, dataset_uuid=uuid, dfs=df)
storage_key = dm.partitions[list(dm.partitions.keys())[0]].files["table"]
filepath = f"{tmpdir}/{storage_key}"
parquet_file = pq.ParquetFile(filepath)
ps = ParquetSerializer()
%timeit ps.restore_dataframe(store_factory(), …
```
=> Improve predicate performance for `in` operator

CHANGES.rst, kartothek/io/eager.py, kartothek/io_components/metapartition.py, tests/io/eager/test_write.py, tests/io_components/test_metapartition.py
This PR makes `io/eager/store_dataframes_as_dataset` accept `dfs` arguments in the following formats:
`{"data": {"table": df}}, {"table": df}, {"data": [("table", df)]}` and `[("table", df)]`.
Docstrings have not been adapted yet.
=> `store_dataframes_as_dataset` accepts dicts and list of tuples equivalents

CHANGES.rst, kartothek/core/index.py, tests/core/test_index.py
=> correctly preserve ExplicitSecondaryIndex dtype when index is empty

CHANGES.rst, kartothek/io/dask/_utils.py, kartothek/io_components/utils.py, tests/serialization/test_filter.py
Running the test ```tests/io/dask/dataframe/test_read.py::test_load_dataframe_categoricals_with_index``` was giving warning ```FutureWarning: Constructing a CategoricalDtype without specifying `ordered` will default to `ordered=False` in a future version; `ordered=None` must be explicitly passed.```
This has been fixed
=> Fix pandas DeprecationWarning

CHANGES.rst, kartothek/io_components/utils.py, tests/io_components/test_utils.py
Normalise properly to lists within normalise_arg
Duplicate of PR #138 but due to its messed up commit history, this new PR
=> Input to `normalize_args` is properly normalized to `list`

CHANGES.rst, docs/further_useful_features.rst, docs/io/examples.rst, kartothek/io/eager.py, tests/io/eager/test_write.py
Added a consistant arg `secondary_indices' to all writing pipelines
=> Added secondary_indices as a default arg

.travis.yml
`pip-compile` wasn't able to figure out that when `dask<2.2.0` is specified it shouldn't get a distributed version which requires a greater version of dask, so we make that clear
=> fix broken build due to pip-compile errors

kartothek/io/eager.py
Up until a few commits ago, passing a single dataframe was supported.
This now re-enables that support but raises a deprecation warning.
This commit also updates the docstring of the function to make the input
clear to a user.
=> update docstring of `io.eager.store_dataframes...` and df arg parsing

CHANGES.rst, kartothek/io/dask/delayed.py, kartothek/io/eager.py, kartothek/io/testing/delete.py, kartothek/io/testing/gc.py, kartothek/io/testing/merge.py, kartothek/io/testing/read.py, kartothek/io/testing/utils.py, tests/conftest.py, tests/io/dask/dataframe/test_read.py, tests/io/dask/delayed/test_read.py, tests/io/eager/test_commit.py, tests/io/eager/test_read.py, tests/io_components/test_metapartition.py, tests/io_components/test_read.py
This PR makes ``read_table`` methods in the ``kartothek.io`` module use the default table name as it is already specified for store/update methods in ``kartothek.io_components.metapartition`` if none is given.
=> Provide default table name for kartothek.io.*read_table* methods

.codecov.yml
The default settings currently highlight all of our builds as failed. I had a look at the past PRs and this threshold is still rather strict but should be forgiving for most trivial coverage decreases.
I don't want to get rid of it immediately since I actually look at the coverage reports every now and then but I want it to be less noisy. If the threshold is too low, we can increase it
=> Add codecov configuration to decrease false negative rate

.travis.yml
We often wait for builds to pass the tests. This commit makes this wait a little bit shorter by marking the build as "passing" (if all required jobs have passed) before the allowed_failures jobs of the build matrix have finished (by default, it waits until the allowed_failures have finished).
Travis docs: https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing
=> enable fast_finish in travis

CHANGES.rst, kartothek/io/testing/write.py, kartothek/io_components/metapartition.py
This should improve overall performance for very large datasets by introducing slots for objects which are created frequently.
The schema validation within the MP seemed quite unnecessary so I removed them. The change in exception messages stems from hashing the schemas at the very final reduction which isn't performed by default.
=> No schema validation in internal ops

CHANGES.rst, kartothek/core/common_metadata.py, tests/core/test_common_metadata.py
Fix an issue where cross-table validation would fail if one of the tables is empty (empty files are allowed as long as there is a file)
=> Allow empty tables to be part of a partition

.travis.yml
The arrow bump enabled the numfocus nighlties to be as required builds. unfortunately, the envs need to match exactly. I.e. we need to be more careful next time
=> allow failures for numfocus nightly again

CHANGES.rst, kartothek/io_components/utils.py, tests/io_components/test_utils.py
I've observed a blowup of parquet file size when using `sort_partitions_by`. The reason is that sorting introduces an int64 index that gets serialized into the Parquet files.
not using `sort_partitions_by`:
```<pyarrow._parquet.ParquetSchema object at 0x7f0eac7f6470>
l_id: INT64
c_date: INT32 DATE
e_type: BYTE_ARRAY UTF8
e_name: BYTE_ARRAY UTF8
```
using `sort_partitions_by`:
```<pyarrow._parquet.ParquetSchema object at 0x7f0ebc625c18>
l_id: INT64
c_date: INT32 DATE
e_type: BYTE_ARRAY UTF8
e_name: BYTE_ARRAY UTF8
__index_level_0__: INT64
```
- [x ] Changelog entry
=> Drop index after sorting so it does not end up in the Arrow table.

LICENSE.txt
They want that to clarify that this is a MIT license and people don't just need to guess from the text or the GitHub auto-detection.
=> add license header as requested by legal

CHANGES.rst, kartothek/io/dask/_update.py, kartothek/io/dask/dataframe.py, tests/io/dask/dataframe/test_update.py
This allows for a deterministic bucketing based on hashing. For large scale data processing this requires a bit more ram (10-20%) but scales very well otherwise.
I would suggest to expose a kwarg `bucket_by` which exposes this parameter publicly and otherwise acts similar to partition_on
=> Hash buckets in update_ddf

kartothek/core/index.py, kartothek/serialization/_generic.py, kartothek/serialization/_parquet.py, tests/core/test_index.py, tests/serialization/test_filter.py
Improve error messages when passing predicate values of wrong type.
Example old:
```
TypeError: Unexpected type encountered. Expected O but got M.
```
Example new:
```
TypeError: Unexpected type for predicate: Column 'col1' has pandas type 'object',
but predicate value Timestamp('2020-01-01 00:00:00') has pandas type 'datetime64[ns]'
(Python type '<class 'pandas._libs.tslibs.timestamps.Timestamp'>').
```
=> Improve predicate TypeError messages

CHANGES.rst, kartothek/io_components/read.py, tests/io_components/test_read.py
This is quite severe and I will immediately release a bug fix version after merge.
For all predicates with multiple values per field this would create duplicate jobs because the `base_df` would look like
```
p
partition
b5c6dc26872c47f2b485b924779537b7  0
b5c6dc26872c47f2b485b924779537b7  1
```
=> Do not produce duplicate jobs when using predicates

CHANGES.rst, kartothek/io/dask/__init__.py, kartothek/io/dask/_sizeof.py
While this doesn't introduce a __sizeof__ implementation for the classes, this registers the classes for the Dask sizeof implementations which enables fast (approximate), recursive size estimations for our objects when used in a dask context.
=> Register classes with dask sizeof

CHANGES.rst, kartothek/serialization/_parquet.py
This section is quite costly when using categorical data. With arrow 0.15.0 both issues where fixed
=> Do not cast dict encoded tables before storage

ci/get_pyarrow_nightly.py
We're supposed to use HTTP Auth now and GitHub is sending me weekly
warning mails about that.
=> Fix GitHub APi deprecation

kartothek/io/dask/bag.py, kartothek/io/dask/delayed.py, kartothek/io/iter.py, kartothek/io/testing/write.py, kartothek/io_components/utils.py
Before this change, user would get error like "Column X missing from dataframe" (because X has been made a partition key already and removed).
=> Nice error message if partition_on and secondary_indices overlap

CHANGES.rst, kartothek/io/dask/_update.py, kartothek/io/dask/_utils.py, kartothek/io/dask/delayed.py
This explicit loop and list creation is pretty slow. See below measurements for a dataset with about 150k partitions, especially when calling this many times this becomes quite an overhead.
The changes in delete are due to partial not properly working if one of the kwargs is a delayed object. Since this is only private the change should be fine
=> Use proper generator for map_delayed

.travis.yml
So our code hasn't been properly tested for the last few PR's as `1 == true` does not evaluate to true in bash (surprise).
=> fix lack of testing in build jobs

.travis.yml
This ensures that the python version specified for the docs job is actually correctly installed.
Previously, the latest python version would be installed as `TRAVIS_PYTHON_VERSION` was unset (see the output of `travis_retry conda create -n test-env --file=conda-requirements.txt --file=conda-test-requirements.txt python=$TRAVIS_PYTHON_VERSION $CONDA_CREATE_ARGS`).
=> fix python install in docs job

.travis.yml, conda-requirements.txt, requirements.txt
I suggest to soon-ish drop support for 0.13.0 and 0.14.1 to not blow up the test matrix. In the same step we can also add py3.8.
For now, I'd like to keep as is and do at least one more release before we cut
=> Run tests for arrow 16

.travis.yml
Master is currently failing. This adds an additional machine readable (i.e. `conda install --file` compatible) output for local reproduction
I kept the original list because it has nicer human readable output. no strong opinion here
=> Dump conda list such that we can recreate environment

kartothek/io/testing/merge.py, kartothek/io/testing/write.py, tests/io/dask/dataframe/test_update.py, tests/io/eager/test_read.py, tests/io_components/test_metapartition.py, tests/serialization/test_dataframe.py, tests/serialization/test_parquet.py
This is deprecated. Minimal supported version of pandas doesn't change since this has been around for a long time
=> Remove deprecated usage of pandas.utils.testing

conda-requirements.txt, conda-test-requirements.txt, requirements.txt, test-requirements.txt
Run use toolz in our own code so we should move it (so far it was implicitly installed via dask)
pytest-flake8 is not used in our configs and if developers prefer this to be installed and used this is an individual choice (similar to pytest-xdist, -profiling, -sugar, etc.)
=> Remove pytest-flake8 and add toolz to runtime dependencies

CHANGES.rst, kartothek/serialization/_parquet.py, tests/io/dask/dataframe/test_read.py, tests/serialization/test_parquet.py
We should ensure that the schema is always as expected.
cc @xhochy is this intended from arrow side that the categorical is returned even though not explicitly requested? Feels awkward with the explicit categories kwarg
=> Fix a type error when reading parquet files with categorical data

CHANGES.rst, kartothek/io/dask/_update.py, tests/conftest.py
I thought this was already part of our test suite... Anyhow we should make sure to avoid the setting with copy warning and raise in our tests if it happens.
=> Do not trigger SettingWithCopyWarning in bucketing

CHANGES.rst, kartothek/core/docs.py, kartothek/core/index.py, kartothek/io/dask/dataframe.py, kartothek/io_components/read.py, kartothek/io_components/utils.py, tests/core/test_docs.py, tests/io/dask/dataframe/test_read.py, tests/io_components/test_read.py
This is a feature I wanted to build for quite some time now and with the `dispatch_by` logic it is, in fact, rather simple
With the `dask_index_on` kwarg it is possible to set the Dask index on a given index column directly which allows for very efficient joins on this column.
=> Reconstruct dask index during loading

kartothek/core/common_metadata.py
This closes the nightly build failures. The issue is that a parquet schema roundtrip adds additional metadata to the fields. This can currently cause problems, especially for nested data types.
We can wait with merging until see https://github.com/apache/arrow/pull/6569 is fixed/resolved. Maybe the nested data types are already resolved there. Then the fixes here would boil down to the fix in `_diff_schemas`
=> fix arrow nightly builds

CHANGES.rst, kartothek/core/common_metadata.py, kartothek/io/eager.py, tests/core/test_common_metadata.py, tests/io/eager/test_update.py
Passing a pyarrow Schema to the create_empty_header function created a corrupt header since the schema was not properly normalised (column/field order).
=> Allow the creation of empty header from pa.Schema

kartothek/core/common_metadata.py, tests/core/test_common_metadata.py
The exact representation of the diffs are not super important and should not break the nightly integration tests (especially not on arrow side)
=> Don't check schema diff for unstable arrow versions

CHANGES.rst, kartothek/io/eager.py
Calling `pandas.DataFrame.reindex` isn't for free even in the case it is a no-op.
cc @mlondschien @jtilly
=> Only fix column ordering if needed

kartothek/io_components/metapartition.py
We are the sole owner of the `DataFrame` in this case and can thus make in-place operations. For larger DataFrames, this was `7s` vs `5us` for me.
cc @mlondschien @jtilly
=> Reset index with range index

kartothek/io_components/metapartition.py
Even running a no-op concat takes some time, so drop this.
cc @mlondschien @jtilly
=> Only concat non-empty index_cols

CHANGES.rst, kartothek/serialization/_parquet.py, tests/serialization/test_parquet.py
We hit these arrow issues is there are empty dict encoded chunked arrays
https://issues.apache.org/jira/browse/ARROW-8142
https://issues.apache.org/jira/browse/ARROW-7907
xref #248
=> Add workaround for ARROW-8142

CHANGES.rst, asv_bench/benchmarks/index.py, kartothek/core/index.py, tests/core/test_index.py, tests/io/dask/dataframe/test_read.py
For most data types the observed values method did not properly work. We should, at some point, refactor the index internals since upon every usage lately we need to convert to an array. I borrowed the logic from the dict-to-array code path. Might be slower but it should be stable
=> Allow dask_index_on for all col types

kartothek/io/eager.py
It seems the current sphinx parser in API really wants some description to be present!
I've added docstrings which will not lead to broken API definition of `delete_dataset`
Link: https://kartothek.readthedocs.io/en/latest/api.html
Given this is an internal change, I felt no need to add a changelog.
=> Add Docstrings to Delete Dataset API

kartothek/core/testing.py, kartothek/io/testing/update.py, kartothek/serialization/_generic.py, tests/serialization/test_filter.py
See commit msgs for details.
There is one notable case left where we test the roundtrip of byte-string columns through pyarrow, likely a leftover from python 2. Since I would like to raise in the serializer in that case and also adjust the tests, this will be done in another PR.
=> Fix some deprecations and other warnings

.pre-commit-config.yaml
master has been red for more than one week due to flake8 pre-commit hook:
```
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1
kartothek/io_components/metapartition.py:140:17: F523 '...'.format(...) has unused arguments at position(s): 1
kartothek/serialization/_parquet.py:304:25: E741 ambiguous variable name 'l'
tests/core/test_dataset_dyn_part.py:357:9: E741 ambiguous variable name 'l'
tests/core/test_dataset_dyn_part.py:407:22: F523 '...'.format(...) has unused arguments at position(s): 0
tests/core/test_dataset_dyn_part.py:428:28: F523 '...'.format(...) has unused arguments at position(s): 0
```
See: https://travis-ci.com/github/JDASoftwareGroup/kartothek/jobs/332586544
This fixes it.
=> fix deprecated flake8 pre-commit hook (fixes red master)

.travis.yml
miniconda needs sometimes a bit more than 30s to install which is then broken by the strict timeout and as the process is not killed hard enough, it gets into an endless loop of being unable to clean up cleanly enough to make a fresh start of the installation.
Fixes #277
=> Increase miniconda installation timeout

CHANGES.rst, kartothek/io/dask/_update.py, kartothek/io/dask/dataframe.py, kartothek/io/dask/delayed.py, tests/io/dask/dataframe/test_update.py
This compresses the payload columns into a single bytestream before shuffle. This has several benefits
* network/disk IO significantly reduced
* intermediate (de)serialization is cheaper
I'm very confident that there is still a lot of room for improvement here but this simple implementation showed already about an order of magnitude better performance on small scale tests. I'll also see if we can get something similar into dask right away.
Credits go to @marco-neumann-jdas for the idea
=> Compress payload columns during shuffle

kartothek/io/dask/dataframe.py
The `karthothek.io.dask.dataframe.load_dataset_as_ddf` does not have a `dispatch_by` argument. It does, however, have a `dask_index_on` argument, which is passed to `dispatch_by` to `kartothek.io.delayed.load_dataset_as_delayed` internally. As dask does not support multiindices, we cannot pass a list of columns to `dask_index_on`, as would be possible with `dispatch_by`. As a proposed solution this PR adds a `dispatch_by` argument to `load_dataset_as_ddf`, which, if no `dask_index_on` is supplied, is passed to `load_dataset_as_delayed`.
=> Add a dispatch_by argument to load_dataset_as_ddf

CHANGES.rst, kartothek/io/dask/_update.py, kartothek/io/dask/dataframe.py, tests/io/dask/dataframe/test_update.py
I caught myself a few times now where I wanted to shuffle without particular `partition_on` In combination with indices and `bucket_by` this allows for some quite powerful dataset layouts. For instance if there are too many unique values of a field to really use `partition_on` but few enough that it makes sense to use indices. There is no technical limitation not to allow this.
This would be a good example for a how to / advanced recipes section now that I think of it...
=> Allow shuffling without partition_on

.travis.yml, conda-requirements.txt, requirements.txt
We're currently still stuck on 0.13.X in some places which is why I don't want to drop the support for the old versions, yet. We're moving on towards 17 and I hope the release following this will be the last one with support for <=15
=> Allow pyarrow==0.17.X

kartothek/io/testing/update.py
- Parametrized ValueError in kartothek.io.testing.update.py to support external testing
=> parametrize value error for external testing backends

CHANGES.rst, kartothek/io/eager.py
Ensure that the `empty_df` also has the right datatype set for categoricals. Otherwise `align_categories` will emit a large number of log messages.
=> Cast categoricals in empty_df in read_table

CHANGES.rst, kartothek/core/docs.py, kartothek/io/dask/bag.py, kartothek/io/dask/delayed.py, kartothek/io/eager.py, kartothek/io/iter.py, kartothek/io/testing/index.py, kartothek/io/testing/read.py, kartothek/io_components/read.py, tests/io_components/test_read.py
I stumbled upon a dataset where the user stores user metadata of about 10kb in the dataset which is perfectly fine imo. However, the dataset itself also has about 100k partitions which generates about 1GB of dummy payload attached to the task graph although this is not used anywhere. This is quite a nonsense feature in the first place and a remnant of the very early days so I'd like to remove this. On the off chance that anybody is using the metapartitions pipeline (soon to be private, I'd suggest) I introduced this feature toggle. All ordinary reader pipelines should only use the simple dispatch
=> Remove dispatch of metadata and indices

asv_bench/benchmarks/index.py, kartothek/core/index.py
The current implementation could take half an hour or so for somewhat larger datasets (20k partitions, 1M entries in index, removing half the partitions). The new implementation provides a speedup in this case of about 1000x.
=> Improve performance for index remove partitions

kartothek/core/dataset.py, kartothek/core/index.py, kartothek/io_components/metapartition.py, tests/io/eager/test_read.py, tests/io_components/test_read.py, tests/serialization/test_filter.py
Predciate evaluation of "OR" connected predicates was not implemented correctly. This could lead to too many files returned by `dispatch_metapartitions`.
Closes #295
=> Fix predicate parsing for "OR" predicates

CHANGES.rst, conda-requirements.txt, kartothek/io/testing/read.py, kartothek/io_components/utils.py, kartothek/serialization/_generic.py, requirements.txt, tests/io/dask/dataframe/test_read.py, tests/serialization/test_dataframe.py, tests/serialization/test_filter.py
Addressing future warnings `is_categorical` and fix tests/adapt to fixed `assert_series_equal` behavior.
=> Update pandas 1.1.0

CHANGES.rst, docs/api.rst, kartothek/io/dask/_update.py, kartothek/io/dask/compression.py, kartothek/io/dask/dataframe.py, tests/io/dask/dataframe/test_compression.py, tests/io/dask/dataframe/test_hashing.py, tests/io/dask/dataframe/test_update.py
This should allow for partition or group based hashing of the data and should make things easier if we need to verify data integrity of some sorts.
I also moved the pack/unpack logic to compress the payload into a public package. I think this can be quite useful outside of "standard" kartothek workflows as long as it's not part of dask, yet
=> Add hash_dataset and make dataframe payload compression functions public

CHANGES.rst, kartothek/core/index.py, tests/core/test_index.py
In a particular test case and a maxRSS background (aka usage before index creation) of
570MB this reduces maxRSS from 1.80GB to 970MB.
=> reduce memory consumption during index write

.github/workflows/ci.yml, CHANGES.rst, conda-requirements.txt, requirements.txt
The released wheel only works for py3.8 :/
This change in CI tests the import of the package before we install the test requirements. Alternatively we could setup a fresh env after wheel build and verify the wheel itself. This one is _probably_ the fastest (haven't verified)
=> Missing typing_extensions requirements

kartothek/core/docs.py, kartothek/serialization/_generic.py, kartothek/serialization/_parquet.py, tests/serialization/test_dataframe.py
Closes #296.
Sorry that I did not get back to this earlier. This implements a simple solution as suggested by @lr4d to filter by missings in predicates. This will not work with `predicate_pushdown_to_io` (see test). I am using `pd.isnull` instead of `np.isnan` as the former works for object columns. Passing `[[("x", "==", np.nan)]]` for an object column will raise an error due to a dtype mismatch, not sure what the expected behaviour would be here. Also not sure what the expected behaviour would be for `<`, `<=`, `>`, `>=` operators together with missings.
=> Allow filtering missings using predicates

CHANGES.rst, kartothek/io/dask/dataframe.py
Without this, the function is already executed once during graph construction to determine the schema
=> Do not call get_parquet_metadata at graph construction time

CHANGES.rst, kartothek/io_components/metapartition.py
This addresses https://issues.apache.org/jira/browse/ARROW-10146 by not relying on the AttributeError. I encountered hitting this for non-empty files which would otherwise cause wrong statistics. I couldn't track down what makes those files special, therefore no test :(
=> Fix get_parquet_metadata sometimes returning empty statistics

kartothek/io/eager.py, kartothek/io_components/utils.py
A bit of maintenance. The `_make_callable` has been replaced by the `lazy_store` which is automatically called by ensure_factory
=> maint: remove utils._make_callable

kartothek/io/dask/bag_cube.py, kartothek/io/dask/common_cube.py, kartothek/io/testing/update_cube.py, tests/io/cube/test_update.py
This adds a new function, `update_cube_from_bag`, which -- similar to other "update" functions -- implements an atomic version of "remove partitions and append".
=> Implement update_cube_from_bag

.github/workflows/ci.yml
Fixes #381
Otherwise `conda` thinks it needs to upgrade the installed `kartothek` version. We otherwise only use conda packages in the CI and thus the best way is to tell conda not to touch any `pip`/`pypi` installed packages instead of guessing what to do with them. The problems in #380 didn't occur much earlier as `conda` always installed the latest release and that was mostly fine in CI.
=> Disable pip interop in CI

CHANGES.rst, kartothek/api/consistency.py, kartothek/api/discover.py, kartothek/core/cube/constants.py, kartothek/core/cube/cube.py, kartothek/io/dask/common_cube.py, kartothek/io/dask/dataframe_cube.py, kartothek/io/testing/append_cube.py, kartothek/io/testing/build_cube.py, kartothek/io_components/cube/write.py, tests/api/test_discover.py, tests/cli/test_info.py, tests/core/cube/test_cube.py, tests/io_components/cube/test_write.py
For large datasets, the automatic index creation can be a performance problem. Also, at some point of dataset size, there is the risk that the 2GB limit pyarrow has is hit. Therefore, it is desirable to switch off thye current default behaviour of creating a secondary index for all dimension columns.
This change would keep the current default of creating an index for all dimension columns. It adds  `cube.suppress_index_on`, which can be set to the subset of dimension columns to suppress the index creation for.
=> cubes: add option to suppress auto index creation for dimension columns

.github/workflows/ci.yml
I was checking if kartothek tested against pandas nightly / rc (to otherwise do a test PR to check pandas 1.2.0rc), and noticed that the current spelling of the pip install didn't actually work to install pandas from the nightly wheels.
=> CI: test pandas nightly

CHANGES.rst, kartothek/core/_zmsgpack.py, requirements.txt
The _zmsgpack.py (kartothek.core.cube) uses zstd module for the compressor and decompressor technique. I have updated the requirements.txt with the module name.
=> fix zstd/zstandard import error

.github/workflows/ci.yml, conda-requirements.txt, kartothek/core/testing.py, kartothek/serialization/testing.py, requirements.txt
The explicitness of the unicode is no longer necessary since we left py2 a long time ago
=> use string data type instead of np.unicode

CHANGES.rst, docs/guide/mutating_datasets.rst, kartothek/api/consistency.py, kartothek/io/dask/_shuffle.py, kartothek/io/dask/bag_cube.py, kartothek/io/dask/common_cube.py, kartothek/io/dask/dataframe.py, kartothek/io/dask/delayed.py, kartothek/io/eager.py, kartothek/io/iter.py, kartothek/io/testing/build_cube.py, kartothek/io/testing/update.py, kartothek/io/testing/update_cube.py, kartothek/io_components/metapartition.py, kartothek/io_components/utils.py, kartothek/io_components/write.py, tests/io/dask/dataframe/test_update.py, tests/io/dask/delayed/test_update.py, tests/io/iter/test_update.py
This fixes an issue where cubes could remove or blacklist index columns and update a dataset/cube. This would then not update said index any longer leaving the dataset in a corrupt state. The only way to consistently deal with this would be to remove the index entirely or to update it. The behaviour for plain datasets, so far, was to update the index regardlessly if the input was omitted. I needed to change that logic slightly but I think the behaviour is still ok. This way the two interfaces area again a bit closer together.
The fix is very pragmatic but everything else would require a rework of the interface and refactoring of a lot of code :/
=> Ensure updates on neither cube nor plain datasets corrupt indices

.codecov.yml, .coveragerc, .github/workflows/ci.yml, conda-test-requirements.txt, test-requirements.txt
This re-enables the asv benchmark tests by parsing output, sets up some caching and fixes the drop in coverage reports which lately fail our PRs for no reasons
the asv and caching is motivated by the pandas ci workflow, see https://github.com/pandas-dev/pandas/blob/9a678df32112fdac7fa082954dd4b44f82d9301c/.github/workflows/ci.yml#L31-L35 and https://github.com/pandas-dev/pandas/blob/9a678df32112fdac7fa082954dd4b44f82d9301c/.github/workflows/ci.yml#L78-L88
=> Caching and asv

CHANGES.rst, kartothek/core/cube/constants.py, kartothek/io/dask/bag_cube.py, kartothek/io/dask/common_cube.py, kartothek/io/dask/dataframe.py, kartothek/io/dask/dataframe_cube.py, kartothek/io/eager.py, kartothek/io/eager_cube.py, kartothek/io/testing/append_cube.py, kartothek/io/testing/build_cube.py, kartothek/io/testing/extend_cube.py, kartothek/io/testing/update_cube.py, kartothek/io/testing/utils.py, kartothek/serialization/_parquet.py, tests/serialization/test_parquet.py
This allows to specify the compression algorithm and a chunk size to
generate row groups.
The Parquet serializer parameter is added the following cube operations:
* `build_cube`
* `append_cube`
* `extend_cube`
* `update_cube`
Specifying different Parquet serializers is back- and forwards compatible.
Row groups are kept for partitions that are not touched during cube operations.
If partitions are replaced or newly created, they are rewritten by the
specified Parquet serializer.
=> Add optional Parquet serializer to cube interface

CHANGES.rst, kartothek/serialization/_io_buffer.py, kartothek/serialization/_parquet.py, tests/serialization/test_parquet.py
Same as in https://github.com/JDASoftwareGroup/kartothek/pull/401
I don't have write access to lr4d's fork, so I can't push on his branch.
Baseline: Add retries for restoring dataframes. We have seen IOErrors on long running ktk + dask tasks with no clear idea what the root cause is. Therefore retry the serialization to gain more stability, until the root cause is fixed.
=> Add retries to restore dataframe

CHANGES.rst, kartothek/io/dask/common_cube.py, tests/io/dask/test_common_cube.py
The issue occured when updating a cube with multiple datasets, which also have different dimension columns.
This fixes issue #413.
The bug is caused by access of a mutated variable - namely `required_indices` via `table_indices` - in the loop. I rewrote the loop to circumvent this problem and added a unit test which verifies that the index validation is working as expected.
=> Fix: Cube index validation (#413)

CHANGES.rst, kartothek/io_components/utils.py, tests/io_components/test_utils.py
The following bug popped up for us today:
```
In [1]: import numpy as np
...: import pandas as pd
...: 
...: from kartothek.io_components.utils import align_categories
...: 
...: df_1 = pd.DataFrame({"letters": ["a", "a", "b", np.nan]})
...: df_2 = pd.DataFrame({"letters": ["a", "a", "b"]})
...: 
...: align_categories([df_1, df_2], ["letters"])
...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-869d9adb16e6> in <module>
7 df_2 = pd.DataFrame({"letters": ["a", "a", "b"]})
8 
----> 9 align_categories([df_1, df_2], ["letters"])
~/code/kartothek/kartothek/io_components/utils.py in align_categories(dfs, categoricals)
362         # use the categories of the largest DF as a …
```
=> Drop missings from fake categories in align categories

CHANGES.rst, kartothek/io_components/metapartition.py, kartothek/io_components/utils.py, tests/io_components/test_metapartition.py
Closes #420 
I did not find a cleaner way to get the list of categoricals. Another option would be to do this within `align_categoricals` is `categoricals=None`.
I am not sure whether the
```python
if len(categoricals) == 0:
return dfs
```
is required to prevent additional copies in absence of categoricals.
=> Fix read_dataset_as_dataframes(_iterator) to correctly return categoricals for misaligned categories

CHANGES.rst, kartothek/core/docs.py, kartothek/core/factory.py, kartothek/io/dask/bag.py, kartothek/io/dask/dataframe.py, kartothek/io/dask/delayed.py, kartothek/io/eager.py, kartothek/io/iter.py, kartothek/io/testing/read.py, kartothek/io_components/cube/query/_regroup.py, kartothek/io_components/gc.py, kartothek/io_components/read.py, kartothek/io_components/utils.py, kartothek/utils/ktk_adapters.py, tests/conftest.py, tests/io/dask/dataframe/test_read.py, tests/io_components/test_read.py
Depends on #431 and removes all deprecated arguments which raised `DeprecationWarnings`
=> Remove deprecated kwargs

kartothek/api/discover.py, kartothek/core/cube/constants.py, kartothek/core/cube/cube.py, kartothek/io/dask/common_cube.py, kartothek/io/testing/cleanup_cube.py, kartothek/io_components/cube/cleanup.py, kartothek/io_components/cube/write.py, tests/core/cube/test_constants.py
Fix two typos, add a comment about ktk/ktk.cube inconsistency
=> fix typo: 'KTK_CUBE_UUID_SEPERATOR' -> 'KTK_CUBE_UUID_SEPARATOR'

kartothek/io/dask/_shuffle.py, kartothek/io/dask/common_cube.py, kartothek/io/dask/dataframe.py, kartothek/io/eager.py, kartothek/io_components/utils.py, kartothek/io_components/write.py
A simplification which is allowed since we removed the indices input in parse_input_*** in #431 The sentinel and mixed type signature of this function is otherwise very confusing
=> Remove inferred indices

CHANGES.rst, kartothek/io/dask/dataframe.py, kartothek/io_components/utils.py, tests/io/dask/dataframe/test_stats.py, tests/io/dask/dataframe/test_update.py
I considered this always as a breaking change since it alters the way dask optimizes the graph which might impact workflows significantly. However, this result should be rather universally better so this is a good change we can safely do with 4.0
This also allows to implement some tree reduction which should speed up the final commit by merging indices in stages instead of one big step in the end but this is not implemented int his PR
=> Return dask scalar for store and update from ddf

CHANGES.rst, kartothek/io/dask/delayed.py, kartothek/io/testing/update.py, kartothek/io_components/metapartition.py, tests/io/dask/dataframe/test_update.py, tests/io_components/test_metapartition.py
When updating a dataset with a table name other than 'table', an additional table named
'table' is erroneously created. This corrupts the dataset. The issue was introduced after
deprecating the table name feature in the 4.0.0 release. The root cause is not passing the
table name as an argument within `partition_on` and `add_metapartition`, which leads to the
default table name "table" being used.
=> Fix dataset corruption after updates (#445)

CHANGES.rst, kartothek/io_components/metapartition.py, tests/io_components/test_metapartition.py
On master:
```
In [1]: import pandas as pd
...: import storefact
...: from functools import partial
...: from kartothek.io.eager import store_dataframes_as_dataset, read_table
...: 
...: path = "/tmp"
...: uuid = "dataset"
...: 
...: df = pd.DataFrame({"w": [-1, -2], "x": [1, 2], "y": ["a", "b"], "z": [0.0, 1.1]})
...: 
...: store = partial(storefact.get_store_from_url, f"hfs://{path}?create_if_missing=False")
...: dm = store_dataframes_as_dataset(
...:     dfs=[df],
...:     dataset_uuid=uuid,
...:     store=store,
...:     partition_on=["w", "x", "y"],
...:     overwrite=True,
...: )
...: 
...: df = read_table(dataset_uuid=uuid, store=store, columns=["y", "z"])
---------------------------------------------------------------------------
IndexError                                Traceback …
```
=> Fix bug when loading few columns of a dataset with many primary indices

docs/spec/indexing.rst
I fixed some mistakes in the documentation:
- In the "Principle in-memory representation" section, the documentation refered to a partition `A=42`, which wasn't introduced before.
- In the "Secondary indices" section, the last sentence wasn't complete. I checked the git log and the file was created like that (https://github.com/JDASoftwareGroup/kartothek/commit/28939c7a56802409f8fbc5f2880796269d8fc84a#diff-5c15d229441c71aed6d9d3f371ab1c6498955d4faa0aa7304e399c1cc7009a2f). Maybe @fjetter still knows what he wanted to write? It's probably something about that the interaction is similar to primary indices. But I didn't want to guess, soI removed it for now.
=> Fix mistakes in documentation

CHANGES.rst, docs/environment-docs.yml, tests/io/dask/dataframe/test_update.py
With #475 we pinned dask do not use 2021.5.1 and 2021.6.0 since they contained known issues (dask/dask#7586).
That issue should have been fixed by https://github.com/dask/dask/pull/7769 which should have been included in >2021.6.0.
However, the the release of dask 2021.6.1, the original issue is gone, but there is another (possibly different) issue.
The message text for empty Dask Data Frames changed in a way that it's dependent on a shuffle operation. See https://github.com/JDASoftwareGroup/kartothek/runs/2880306923?check_suite_focus=true for the exact error messages.
This PR proposes to check for all 3 kind of error message to make sure the test runs with all dask versions and indepedently of the `shuffle` parameter. I decided against checking only for `ValueError` because then we might …
=> Fix test by matching error messages appearing from dask > 2021.5.0, fix documentation build and prepare release 5.0

CHANGES.rst, kartothek/utils/converters.py, kartothek/utils/predicate_converter.py, tests/utils/test_predicate_converter.py
Adding a helper module in utils to convert a kartothek read dataset predicate to a query cube predicate.
This functionalities makes integrations from querying datasets to querying cubes easier, and also will be handy for libraries loading both data from datasets and cubes.
=> contribution / Add predicates to conditions converter

CHANGES.rst, kartothek/io/dask/_utils.py
Removing warning which could never have succeed because it was syntactically wrong
=> Fixed error of wrong type by removing warning for distinct categoricals
