docs/spec/index.rst

replaced OBST acronym to be more broadly understandable

Improved documentation

---

.gitignore
CONTRIBUTING.md
asv_bench/benchmarks/metapartition.py
asv_bench/benchmarks/schema.py
asv_bench/benchmarks/write.py
test-requirements.in

Make kartothek better for new contributors.

Fix contribution-related issues

---

CHANGES.rst
kartothek/core/_mixins.py
kartothek/core/index.py
kartothek/io_components/docs.py
kartothek/io_components/metapartition.py
kartothek/serialization/_generic.py
requirements.in
tests/conftest.py
tests/core/test_index.py

See individual commits for details.

Fix warnings and other quality-of-life improvements.

---

.isort.cfg
.pre-commit-config.yaml
pyproject.toml
test-requirements.in

Since https://github.com/timothycrosley/isort/issues/763 has been fixed

move config in `.isort.cfg` to `pyproject.toml` under the section `[tool.isort]`

---

.gitignore
.pre-commit-config.yaml
kartothek/core/testing.py
kartothek/io/testing/read.py
kartothek/serialization/_generic.py
mypy.ini

set up mypy

---

docs/spec/index.rst
kartothek/core/_compat.py
kartothek/core/common_metadata.py
kartothek/core/dataset.py
kartothek/core/index.py
kartothek/core/testing.py
kartothek/core/uuid.py
kartothek/io/eager.py
kartothek/io/testing/delete.py
kartothek/io_components/utils.py
kartothek/io_components/write.py
tests/serialization/test_arrow_compat.py

Found by `misspell -error kartothek tests docs/*.rst docs/io docs/spec/`

fix some spelling issues

---

kartothek/core/_zmsgpack.py
kartothek/core/common_metadata.py
kartothek/core/dataset.py
kartothek/io/eager.py
kartothek/io/iter.py
kartothek/io_components/metapartition.py
kartothek/io_components/read.py
kartothek/io_components/utils.py

I tried out [pytype](https://google.github.io/pytype/) as an alternative to [mypy](http://mypy-lang.org/). In comparison, it is very slow but can infer signatures that we have not added yet. By doing so, it found some interesting edge cases that I am fixing in this PR. If you're interested in another comparison, you can watch [this 5min lightning talk](https://www.youtube.com/watch?v=yFcCuinRVnU&t=38m25s).

Fix pytype errors

---

.pre-commit-config.yaml
docs/getting_started.rst
docs/io/examples.rst

This runs `blacken-docs` (https://github.com/asottile/blacken-docs), i.e. `black` on Python code blocks in `rst` and `md` files

Blacken docs pre commit

---

docs/further_useful_features.rst
docs/getting_started.rst
docs/index.rst
docs/io/index.rst
docs/spec/predicate_pushdown.rst

Major re-write
Added:
- Update section
- GC
- Partition/Indices
Improved:
- Write
- Read
- Storage
With input from @kagharpure . He may be able to apply requested changes if necessary.

re-write getting started guide

---

requirements.txt

As agreed in #81 , blacklist pyarrow=0.14.0

blacklist pyarrow=0.14.0

---

.travis.yml

Pin pip in build chain

---

CHANGES.rst
kartothek/serialization/_generic.py
tests/core/test_index.py
tests/serialization/test_filter.py

Type stability pred pushdown

---

.travis.yml
ci/before_install.sh
ci/compile_requirements.sh

Using the osx image's default python3.

Add osx to testing environments

---

.github/issue_template.md
.github/pull_request_template.md

This should be picked up by GitHub and be used as issue/PR templates.
Especially for PRs the `Closes` is important since this will trigger GitHub to automatically close an issue when the PR is merged

Issue and PR templates

---

.travis.yml
CHANGES.rst
kartothek/io_components/metapartition.py
tests/io_components/test_metapartition.py

Fixes the segfault cause by https://issues.apache.org/jira/browse/ARROW-5873

Avoid shema comparison to None

---

kartothek/serialization/_generic.py
kartothek/serialization/testing.py

remove unnecesary code

---

.travis.yml
ci/before_install.sh
ci/compile_requirements.sh
ci/get_pyarrow_nightly.py

Nightly pandas, numpy and arrow integration

---

requirements.txt

The version before this had packaging issues and race conditions when threading

Increase minimal version for urlquote

---

CHANGES.rst
kartothek/io_components/docs.py
tests/io_components/test_docs.py

Given that there are no doc-tests, it's a little hard to tell if this implementation is not going to lead unforeseen bugs.
- Closes #145

Fix broken docstring parser and add test case

---

.travis.yml
CHANGES.rst
kartothek/core/_compat.py
kartothek/core/common_metadata.py
kartothek/serialization/_arrow_compat.py
kartothek/serialization/_parquet.py
requirements.txt
tests/core/test_common_metadata.py
tests/core/test_dataset_dyn_part.py
tests/serialization/test_parquet.py

Remove pyarrow 0.12.x support

---

kartothek/io/iter.py
tests/io_components/test_docs.py

This fixes the broken test case that was produced in PR#146

Fix broken test case

---

CHANGES.rst
kartothek/core/index.py
kartothek/io_components/metapartition.py
kartothek/io_components/read.py
tests/core/test_index.py
tests/io/dask/conftest.py

fix ArrowNotImplementedError for empty indices

---

CHANGES.rst
kartothek/core/docs.py
kartothek/io/dask/bag.py
kartothek/io/dask/delayed.py
kartothek/io/eager.py
kartothek/io/iter.py
kartothek/io_components/utils.py
tests/core/test_docs.py

Update docstrings 
Make test cases for default_docs more robust

Update docs and make test cases more robust

---

CHANGES.rst
kartothek/core/factory.py
kartothek/io/eager.py
kartothek/io_components/utils.py

Related to https://github.com/JDASoftwareGroup/kartothek/issues/186

Type eager module

---

CHANGES.rst
kartothek/io/dask/_update.py
tests/io/dask/dataframe/test_update.py

The update function would not remove the internal column

Remove _KTK_HASH_BUCKET if exists

---

.codecov.yml
.coveragerc

The pytest report generation was including unwanted folders and files.

Fix Code Coverage Report

---

tests/serialization/test_filter.py

add xfail tests for gh-193

---

.travis.yml
conda-test-requirements.txt
test-requirements.txt

Failure was caused because of hypothesis >=5.2.0, apparently strings are generated in a way which cuases an exception in numpy

Fix red master

---

conda-test-requirements.txt
test-requirements.txt

See comment in #205 for reasoning.

unpin hypothesis

---

kartothek/io/eager.py

Add type annotations to `eager/read_table`.

Add type annotations to eager/read_table

---

.travis.yml
conda-requirements.txt
docs/further_useful_features.rst
docs/spec/type_system.rst
requirements.txt

Pandas 1.0.1 will be out in a few days. This currently breaks important functionality (nightlies are already green-ish)

Pin pandas 1.0.0 due to an upstream bug

---

.travis.yml

fix .travis.yml excluding os x jobs

---

kartothek/io_components/read.py
kartothek/serialization/_generic.py

Extracts more typings from #243

Type dispatch_metapartitions

---

kartothek/io_components/metapartition.py

Only subset columns if table_columns are a strict subset

---

docs/guide/partitioning.rst
kartothek/io/dask/dataframe.py

This adds a warning about the data shuffling method since this is a surprise and hard to debug.

Add warning about shuffle method

---

kartothek/io/testing/read.py

Fixes #234 
Depends on https://github.com/apache/arrow/pull/6665

Add a test for roundtripping ExtensionArrays

---

CHANGES.rst
kartothek/io_components/metapartition.py
kartothek/serialization/_parquet.py

some small performance improvements

---

kartothek/io/dask/dataframe.py

fix documentation

---

CHANGES.rst
kartothek/io/testing/update.py
kartothek/io_components/metapartition.py
tests/io/dask/dataframe/test_update.py
tests/io_components/test_metapartition.py

raise when trying to partition on column with nulls

---

.gitignore
CHANGES.rst
kartothek/core/index.py
kartothek/io/testing/index.py
kartothek/io_components/metapartition.py
tests/conftest.py

Bunch of fixes for index type handling

---

.travis.yml

Pull Arrow nightlies from arrow-nightlies

---

kartothek/io/dask/dataframe.py

Add default table to load_dataset_as_ddf and update_dataset_from_ddf

---

reference-data/arrow-compat/batch_generate_references.sh
tests/serialization/test_arrow_compat.py

update reference Parquet generation scripts

---

kartothek/io/dask/_update.py
tests/io/dask/dataframe/test_update.py

Not sure if we should make this function public and if so: where it should live.

fix unpack_payload and add tests

---

.travis.yml

Since three months they are only uploaded there.

Change to new NumFOCUS nightly wheels location

---

.pre-commit-config.yaml
docs/spec/serialization.rst
kartothek/core/common_metadata.py
kartothek/core/index.py
kartothek/io/dask/_update.py
kartothek/io_components/metapartition.py
kartothek/serialization/_generic.py
kartothek/serialization/_parquet.py
tests/core/test_dataset_dyn_part.py
tests/io/dask/dataframe/test_update.py

Update pre-commit hooks

---

.github/workflows/ci.yml

do not fail CI for nightly-related jobs

---

CHANGES.rst
conda-requirements.txt
kartothek/api/discover.py
kartothek/core/cube/constants.py
kartothek/io_components/cube/query/_intention.py
kartothek/io_components/cube/query/_regroup.py
kartothek/utils/ktk_adapters.py
kartothek/utils/pandas.py
kartothek/utils/store.py
requirements.txt
setup.py
tests/api/test_discover.py
tests/cli/test_base.py
tests/cli/test_info.py
tests/test_modules.py
tests/utils/test_ktk_adapters.py
tests/utils/test_store.py

- Updated Timestamp related code into Ktk Cube.
- Added compatibility for old cubes with respect to the params and constants.
- Updated changelog
- Downpinned pandas<1.1 version.

updation of timestamp related code into ktk

---

.github/workflows/ci.yml

So nobody needs to do this manually.

automate GitHub releases

---

conda-test-requirements.txt
kartothek/api/consistency.py
kartothek/api/discover.py
kartothek/core/index.py
test-requirements.txt

Fix master.

---

kartothek/io/eager.py

While using the documentation, I notice that the wrong function was imported.

fixed import in documentation

---

CHANGES.rst
kartothek/core/index.py
kartothek/io/testing/read.py
kartothek/io/testing/write.py
tests/core/test_utils.py

This is a regression to 3.14.X. defining a store callable with a non serializable store would raise.

Fix nonserializable store regression

---

CHANGES.rst
kartothek/io/dask/dataframe.py
tests/io/dask/dataframe/test_repartition.py

Addition of  calculation of  re-partition ratio and optimize functionality to Ktk

Addition of repartition ratio calculation and optimize functionality to Ktk

---

CHANGES.rst
kartothek/io/eager_cube.py
kartothek/io_components/cube/remove.py
tests/io/cube/test_remove.py

Fix cube remove_partitions with conditions that match no partition

---

CHANGES.rst
kartothek/io/eager.py
kartothek/io_components/utils.py
tests/io/eager/test_commit.py

this allows to modify user metadata post dataset creation safely
@mlondschien would this work for you?

Allow metadata modification using commit_dataset

---

CHANGES.rst
kartothek/core/utils.py
kartothek/io/dask/common_cube.py
tests/core/test_utils.py

Fix conversion of 'store' argument

---

kartothek/serialization/_io_buffer.py

We've seen some failures in the parquet read path hitting an assertion error. Unfortunately, it is not clear which assert was hit, as pyarrow swallows that part of the error message. However, for the few assert in kartothek that could be hit here (?), let's make sure they are more noisy.

serialization: add logging in case assertions in io buffer fail

---

.github/workflows/ci.yml
kartothek/core/index.py
kartothek/io/testing/query_cube.py
tests/io/cube/conftest.py
tests/io/cube/test_query.py

fix master

---

CHANGES.rst
kartothek/io/dask/bag.py
kartothek/io/dask/delayed.py
kartothek/io/iter.py
kartothek/io/testing/read.py
kartothek/io_components/read.py
kartothek/io_components/utils.py

Closes #368 
Not sure why `mypy` wasn't complaining before. Tests and Changelog are still open.

Correctly handle dispatch_by=[]

---

CHANGES.rst

Prepare changelog for release `3.19.0`

Prepare changelog for relesae 3.19.0

---

CHANGES.rst

Prepare changelog v3.19.1

---

kartothek/core/testing.py
kartothek/serialization/testing.py
tests/core/test_common_metadata.py

These are deprecated aliases with numpy 1.20

Deal with numpy deprecations

---

CHANGES.rst
docs/conf.py
kartothek/core/dataset.py

add schema attribute to DatasetMetadataBase

---

kartothek/io/testing/read.py
kartothek/io/testing/write.py
kartothek/io_components/metapartition.py
kartothek/io_components/read.py

This is a regression which was introduced by #431

Add tests for non-default table

---

CHANGES.rst

Prepare release 4.0.1

---

CHANGES.rst

Prepare changelog for v5.1.0

---

.github/workflows/ci.yml
docs/environment-docs.yml
requirements.txt
tests/io/dask/dataframe/test_update.py

4.x: Test against pyarrow 4

---

CONTRIBUTING.md

Improve setup documentation for conda and the docs build process to the CONTRIBUTING.md resource.

Improve docs setup documentation

---

.github/workflows/ci.yml
CHANGES.rst

Update release data for 5.20 and disable fail-fast for the tests

Prepare release 5.2.0

---

CHANGES.rst
asv_bench/benchmarks/write.py
conda-requirements.txt
docs/conf.py
docs/environment-docs.yml
kartothek/core/dataset.py
kartothek/core/factory.py
kartothek/io/dask/_shuffle.py
kartothek/io/dask/bag.py
kartothek/io/dask/dataframe.py
kartothek/io/dask/delayed.py
kartothek/io/eager.py
kartothek/io/iter.py
kartothek/io_components/merge.py
kartothek/io_components/metapartition.py
kartothek/io_components/read.py
kartothek/io_components/utils.py
kartothek/io_components/write.py
kartothek/utils/ktk_adapters.py
kartothek/utils/migration_helpers.py
requirements.txt
setup.cfg
tests/utils/test_migration_helpers.py

Add decorators for deprecation warning handling of entire functions and individual parameters.
Current state: WIP

Deprecation decorators and warnings for the 5.3 version.
